name = "bodyshapecoach-bot"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_TOKEN_HERE"
OPENAI_API_KEY = "YOUR_OPENAI_KEY_HERE"

kv_namespaces = [
  { binding = "BodyShapeCoach-bot-worker", id = "5f968b0074ee47948f40063ec8cbeeda" }
]
[workflows]
name = "telegram-bot-workflow"
binding = "MY_WORKFLOW"
class_name = "TelegramBotWorkflow"
